# Generated by Django 3.2.9 on 2021-12-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_booksearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.book')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.category')),
            ],
        ),
    ]
